from __future__ import annotations

from typing import Annotated, AsyncIterator, Literal, TypedDict

from langgraph.graph import END, StateGraph

from models import AgentEvent, AdGenerationResult, Product
from tools import generate_image_tool, generate_prompt_tool, get_inventory_tool


class AdGenerationState(TypedDict):
    product_id: Annotated[str | None, "Product requested by the user"]
    product: Annotated[dict | None, "Selected inventory product"]
    platform: Annotated[str, "Target ad platform"]
    style: Annotated[str, "Visual style for the advertisement"]
    audience: Annotated[str | None, "Target customer segment"]
    cta: Annotated[str, "Call to action"]
    inventory_source: Annotated[Literal["mcp", "fallback"] | None, "Inventory source used"]
    ad_prompt: Annotated[str | None, "Prompt generated by the prompt agent"]
    image_url: Annotated[str | None, "Final image advertisement URL"]
    errors: Annotated[list[str], "Recoverable errors gathered during the run"]


async def inventory_agent(state: AdGenerationState) -> AdGenerationState:
    inventory = await get_inventory_tool.ainvoke({})
    products = inventory.get("products", [])
    selected = None
    if state.get("product_id"):
        selected = next((item for item in products if item.get("id") == state["product_id"]), None)
    selected = selected or (products[0] if products else None)
    errors = list(state.get("errors", []))
    if inventory.get("error"):
        errors.append(inventory["error"])
    if not selected:
        errors.append("No product was available from inventory sources.")
    return {
        **state,
        "product": selected,
        "inventory_source": inventory.get("source", "fallback"),
        "errors": errors,
    }


async def prompt_agent(state: AdGenerationState) -> AdGenerationState:
    product = state.get("product") or {}
    prompt_result = await generate_prompt_tool.ainvoke(
        {
            "product": product,
            "platform": state["platform"],
            "style": state["style"],
            "audience": state.get("audience"),
            "cta": state["cta"],
        }
    )
    errors = list(state.get("errors", []))
    if prompt_result.get("error"):
        errors.append(f"Prompt agent fallback used: {prompt_result['error']}")
    return {**state, "ad_prompt": prompt_result.get("ad_prompt", ""), "errors": errors}


async def image_agent(state: AdGenerationState) -> AdGenerationState:
    image_result = await generate_image_tool.ainvoke({"ad_prompt": state.get("ad_prompt") or ""})
    errors = list(state.get("errors", []))
    if image_result.get("error"):
        errors.append(f"Image agent fallback used: {image_result['error']}")
    return {**state, "image_url": image_result.get("image_url", ""), "errors": errors}


def build_graph():
    graph = StateGraph(AdGenerationState)
    graph.add_node("inventory_agent", inventory_agent)
    graph.add_node("prompt_agent", prompt_agent)
    graph.add_node("image_agent", image_agent)
    graph.set_entry_point("inventory_agent")
    graph.add_edge("inventory_agent", "prompt_agent")
    graph.add_edge("prompt_agent", "image_agent")
    graph.add_edge("image_agent", END)
    return graph.compile()


async def run_workflow(payload: dict) -> AdGenerationResult:
    app = build_graph()
    final_state = await app.ainvoke(
        {
            "product_id": payload.get("product_id"),
            "product": None,
            "platform": payload.get("platform", "Instagram"),
            "style": payload.get("style", "premium social media ad"),
            "audience": payload.get("audience"),
            "cta": payload.get("cta", "Shop now"),
            "inventory_source": None,
            "ad_prompt": None,
            "image_url": None,
            "errors": [],
        }
    )
    return AdGenerationResult(
        product=Product.model_validate(final_state["product"]),
        ad_prompt=final_state["ad_prompt"] or "",
        image_url=final_state["image_url"] or "",
        inventory_source=final_state["inventory_source"] or "fallback",
        errors=final_state["errors"],
    )


async def stream_workflow_events(payload: dict) -> AsyncIterator[AgentEvent]:
    yield AgentEvent(agent="inventory", status="running", message="Connecting to inventory source...")
    inventory_state = await inventory_agent(
        {
            "product_id": payload.get("product_id"),
            "product": None,
            "platform": payload.get("platform", "Instagram"),
            "style": payload.get("style", "premium social media ad"),
            "audience": payload.get("audience"),
            "cta": payload.get("cta", "Shop now"),
            "inventory_source": None,
            "ad_prompt": None,
            "image_url": None,
            "errors": [],
        }
    )
    inv_status = "fallback" if inventory_state["inventory_source"] == "fallback" else "complete"
    yield AgentEvent(
        agent="inventory",
        status=inv_status,
        message="Product context ready for the prompt agent.",
        output={"product": inventory_state["product"], "source": inventory_state["inventory_source"]},
    )

    yield AgentEvent(
        agent="prompt",
        status="running",
        message="Generating a detailed master prompt from product data, platform, creative style, and CTA...",
    )
    prompt_state = await prompt_agent(inventory_state)
    yield AgentEvent(
        agent="prompt",
        status="complete",
        message="Master prompt generated and handed to the image agent.",
        input={
            "product": prompt_state["product"],
            "platform": prompt_state["platform"],
            "style": prompt_state["style"],
            "cta": prompt_state["cta"],
        },
        output={"master_prompt": prompt_state["ad_prompt"]},
    )

    yield AgentEvent(agent="image", status="running", message="Generating advertisement image from the master prompt...")
    image_state = await image_agent(prompt_state)
    yield AgentEvent(
        agent="image",
        status="complete",
        message="Image advertisement URL is ready.",
        input={"master_prompt": image_state["ad_prompt"]},
        output={"image_url": image_state["image_url"]},
    )

    yield AgentEvent(
        agent="workflow",
        status="complete",
        message="Pipeline complete.",
        output={
            "product": image_state["product"],
            "ad_prompt": image_state["ad_prompt"],
            "image_url": image_state["image_url"],
            "inventory_source": image_state["inventory_source"],
            "errors": image_state["errors"],
        },
    )
